name: Build release Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  verify_build:
    uses: ./.github/workflows/verify-build.yml

  build_docker_image:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: verify_build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Trigger webhook
      run: |
        echo ${{ secrets.ACTIONS_WEBHOOK }}
        # # # curl -d '{"content": "Hello from an action"}' -H "Content-Type: application/json" -X POST ${{ secrets.ACTIONS_WEBHOOK }}

    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.AUTH_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true

