name: Build release Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  verify_build:
    name: Verify build
    uses: ./.github/workflows/verify-build.yml

  build_docker_image:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    name: Build docker image
    runs-on: ubuntu-latest
    needs: verify_build
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tag version - semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AUTH_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.semantic.outputs.new_release_version }}
          build-args: |
            NEW_VERSION=${{ steps.semantic.outputs.new_release_version }}

  # send_report:
  #   name: Send workflow report
  #   needs: build_docker_image
  #   env:
  #     docker_image_status: ${{ needs.build_docker_image.result }}
  #     docker_image_name: ghcr.io/${{ github.repository }}:${{ steps.semantic.outputs.new_release_version }}
  #   uses: ./.github/workflows/report.yml
