name: Build release Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  verify_build:
    uses: ./.github/workflows/verify-build.yml

  build_docker_image:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: verify_build
    continue-on-error: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.AUTH_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Send report
      uses: ./.github/workflows/report.yml